# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Glorin_Sinuosity
                                 A QGIS plugin
 This plugin is designed to find the sinuosity on any segment of river as well as finding environmental stats for the surrounding area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-14
        copyright            : (C) 2026 by Jacob Freeman
        email                : freeman0898@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# Portions of this file are derived from the QGIS Earth Engine Plugin
# (https://github.com/gee-community/qgis-earthengine-plugin),
# Copyright (c) 2019 Gennadii Donchyts, licensed under the MIT License.


import configparser
import os, sys
import site

_ext = os.path.join(os.path.dirname(__file__), "extlibs")
if os.path.isdir(_ext) and _ext not in sys.path:
    sys.path.insert(0, _ext)

def _plugin_version() -> str:
    cfg = configparser.ConfigParser()
    cfg.read(os.path.join(os.path.dirname(__file__), "metadata.txt"))
    try:
        return cfg.get("general", "version")
    except configparser.NoOptionError:
        return "0.0.0-dev"
        
        
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Glorin_Sinuosity class from file Glorin_Sinuosity.
    """
    #
    from .glorin_sinuosity import Glorin_Sinuosity
    ee_config = config.EarthEngineConfig()
    return Glorin_Sinuosity(iface, ee_config=ee_config)
    
