# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Glorin_Sinuosity
                                 A QGIS plugin
 This plugin is designed to find the sinuosity on any segment of river as well as finding environmental stats for the surrounding area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Jacob Freeman
        email                : freeman0898@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# Portions of this file are derived from the QGIS Earth Engine Plugin
# (https://github.com/gee-community/qgis-earthengine-plugin),
# Copyright (c) 2019 Gennadii Donchyts, licensed under the MIT License.


import configparser
import json
import os.path
import webbrowser
from typing import cast

import requests
from qgis import gui, processing
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, Qt
from qgis.core import QgsSettings, QgsProject, QgsApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QAction
import ee

# Import the code for the dialog
from . import  provider, config, ee_auth1, utils, logging
from .ui import menus
from . processing.processing_provider import GlorinProcessingProvider
from . processing.sinuosity import SinuosityAlgorithm
from . processing.River_analysis import RiverAnalysisAlgorithm
from . processing.segmented_analysis import SegmentedRiverAnalysisAlgorithm

    
PLUGIN_DIR = os.path.dirname(__file__)

# read the plugin version from metadata
cfg = configparser.ConfigParser()
cfg.read(os.path.join(PLUGIN_DIR, "metadata.txt"))

try:
    VERSION = cfg.get("general", "version")
except configparser.NoOptionError:
    # if version is not set, use a default value
    VERSION = "0.0.0-dev"

version_checked = False


def _parse_version(version: str) -> tuple[int, ...]:
    normalized = version.strip().lstrip("v")
    return tuple(int(part) for part in normalized.split("."))


def icon(icon_name: str) -> QIcon:
    """Helper function to return an icon from the plugin directory."""
    return QIcon(os.path.join(PLUGIN_DIR, "icons", icon_name))


class Glorin_Sinuosity:
    
    ee_config: config.EarthEngineConfig
    
    def __init__(self, iface: gui.QgisInterface, ee_config: config.EarthEngineConfig):
        
        # Save reference to the QGIS interface
        self.iface = iface
        self.ee_config = ee_config
        self.menu = None
        self.toolButton = None
        self.toolButtonAction = None
        self.identify_action = None
        self.identify_tool = None
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Glorin Sinuosity')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        #Create and register the EE data providers
        provider.register_data_provider()
        
        # Reload the plugin when the config changes
        self.ee_config.signals.updated.connect(
            lambda: self.set_cloud_project_action.setText(
                self.tr(self._project_button_text)
            )
        )
        
        logging.setup_logger(plugin_name= "Glorin Sinuosity Plugin")

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Glorin_Sinuosity', message)



    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        self.provider = GlorinProcessingProvider(icon=icon("Warisin.png"))
        QgsApplication.processingRegistry().addProvider(self.provider)

        # will be set False in run()
        self.first_start = True

        sign_in_action = QtWidgets.QAction(
            text=self.tr("Sign-in"),
            parent=self.iface.mainWindow(),
            triggered=self._run_cmd_sign_in,
        )
        self.set_cloud_project_action = QtWidgets.QAction(
            text=self.tr(self._project_button_text),
            parent=self.iface.mainWindow(),
            triggered=self._run_cmd_set_cloud_project,
        )
        
        segmented_analysis_button = QtWidgets.QAction(
        text=self.tr("Segmented River Analysis"),
        parent=self.iface.mainWindow(),
        triggered = lambda: processing.execAlgorithmDialog("glorin:segmented_river_analysis"),)
        
        sinuosity_button = QtWidgets.QAction(
        text=self.tr("Measure Sinuosity"),
        parent = self.iface.mainWindow(),
        triggered=lambda: processing.execAlgorithmDialog("glorin:Sinuosity"),)
        
        river_analysis_button = QtWidgets.QAction(
        text=self.tr("River Analysis"),
        parent=self.iface.mainWindow(),
        triggered=lambda: processing.execAlgorithmDialog("glorin:river_analysis"),)
        
        plugin_menu = cast(QtWidgets.QMenu, self.iface.pluginMenu())
        self.menu = plugin_menu.addMenu(
            self.tr("&Glorin Sinuosity"),
        )
        # Initialize EE after GUI is ready
        try:
            ee_auth1.ensure_authenticated(self.ee_config)
            ee_auth1.ee_initialize_with_project(self.ee_config)
        except Exception as e:
            # Log the error but don't crash the plugin
            import traceback
            traceback.print_exc()
            
        # Initialize toolbar menu
        self.toolButton = QtWidgets.QToolButton()
        self.toolButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.toolButton.setPopupMode(
            QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup
        )
        self.toolButton.setMenu(QtWidgets.QMenu())
        self.toolButton.setDefaultAction(
            QtWidgets.QAction(
                icon=icon("Warisin.png"),
                text=f"<strong>{self.tr('Glorin Sinuosity')}</strong>",
                parent=self.iface.mainWindow(),
            )
        )
        self.toolButtonAction = self.iface.pluginToolBar().addWidget(self.toolButton)
        
        #populate menus
        for m in (self.menu, self.toolButton.menu()):
            menus.populate_menu(
            menu=m,
            items=[
            menus.Action(action=sign_in_action),
            menus.Action(action=self.set_cloud_project_action),
            menus.Separator(),
            menus.Action(action=sinuosity_button),
            menus.Action(action=river_analysis_button),
            menus.Action(action=segmented_analysis_button)])        
        
    def unload(self):
        
        for name in ('sign_in_action', 'set_cloud_project_action',
                 'segmented_analysis_button', 'sinuosity_button',
                 'river_analysis_button'):
            act = getattr(self, name, None)
            if act is not None:
                self.menu.removeAction(act)
                self.toolButton.menu().removeAction(act)
                
        if getattr(self, 'toolButtonAction', None) is not None:
            self.iface.pluginToolBar().removeAction(self.toolButtonAction)
        if getattr(self, 'toolButton', None) is not None:
            self.toolButton.deleteLater()


    @property
    def _project_button_text(self):
        """Get the text for the project button."""
        return f"Set Project: {self.ee_config.project or '...'}"
        
    def _run_cmd_sign_in(self):
        import ee

        # reset authentication by forcing sign in
        ee.Authenticate(auth_mode="localhost", force=True)

        # after resetting authentication, select Google Cloud project again
        self._run_cmd_set_cloud_project()

    def _run_cmd_set_cloud_project(self):
        ee_auth1.ee_initialize_with_project(self.ee_config, force=True)    
